import React, { useEffect, useMemo, useState } from 'react';
import {
  FilePlus2,
  Calendar,
  Clock,
  CheckCircle2,
  XCircle,
  RotateCcw,
  FileText,
  Download,
  Search,
  AlertTriangle,
  Send,
  Save,
  Loader2,
  Eye,
  Edit3,
  Ban,
  ExternalLink,
  CheckCheck,
} from 'lucide-react';
import {
  InspectorRecord,
  LeaveDurationType,
  LeaveRequest,
  LeaveType,
  SystemSettings,
  User,
} from '../types.ts';
import {
  calculateLeaveDays,
  formatThaiDate,
  getThaiMonthName,
  getTodayISO,
  parseISODateParts,
} from '../utils/thaiDate.ts';
import { generateOfficialLeavePdf } from '../utils/pdfGenerator.ts';
import { OfficialLeaveDocument } from './OfficialLeaveDocument.tsx';
import { SignaturePad } from './SignaturePad.tsx';

const LOCAL_DRAFT_KEY = 'namphong_leave_form_draft_v1';

interface CreateOrEditLeaveViewProps {
  user: User;
  settings: SystemSettings;
  leaveTypes: LeaveType[];
  existingLeaves?: LeaveRequest[];
  inspectors?: InspectorRecord[];
  editingLeave?: LeaveRequest | null;
  onSubmitLeave: (payload: any, existingLeaveId?: string) => Promise<LeaveRequest>;
  onUploadPdfToDrive: (
    leaveId: string,
    pdfBase64: string,
    fileName: string
  ) => Promise<LeaveRequest | void>;
  onCancelEdit?: () => void;
  onFinished: (createdLeave: LeaveRequest) => void;
}

export const CreateOrEditLeaveView: React.FC<CreateOrEditLeaveViewProps> = ({
  user,
  settings,
  leaveTypes,
  existingLeaves = [],
  inspectors = [],
  editingLeave,
  onSubmitLeave,
  onUploadPdfToDrive,
  onCancelEdit,
  onFinished,
}) => {
  const activeLeaveTypes = useMemo(
    () => leaveTypes.filter((lt) => lt.isActive),
    [leaveTypes]
  );

  const defaultType = activeLeaveTypes[0] || leaveTypes[0];

  const [viewMode, setViewMode] = useState<'split' | 'form' | 'a4_preview'>('split');
  const [writtenDate, setWrittenDate] = useState(editingLeave?.writtenDate || getTodayISO());
  const [leaveTypeId, setLeaveTypeId] = useState(
    editingLeave?.leaveTypeId || defaultType?.typeId || 'LT-01'
  );
  const [subject, setSubject] = useState(
    editingLeave?.subject || `ขออนุญาต${defaultType?.name || 'ลาป่วย'}`
  );
  const [addressedTo, setAddressedTo] = useState(
    editingLeave?.addressedTo || settings.addressedToDefault || 'ผู้อำนวยการสกร.ระดับอำเภอน้ำพอง'
  );
  const [requesterPosition, setRequesterPosition] = useState(
    editingLeave?.position || user.position || ''
  );
  const [requesterDepartment, setRequesterDepartment] = useState(
    editingLeave?.department || user.department || settings.organizationName || 'สกร.ระดับอำเภอน้ำพอง จ.ขอนแก่น'
  );
  const [durationType, setDurationType] = useState<LeaveDurationType>(
    editingLeave?.durationType || 'เต็มวัน'
  );
  const [startDate, setStartDate] = useState(editingLeave?.startDate || getTodayISO());
  const [endDate, setEndDate] = useState(editingLeave?.endDate || getTodayISO());
  const [excludeWeekends, setExcludeWeekends] = useState(false);
  const [reason, setReason] = useState(editingLeave?.reason || '');
  const [contactAddress, setContactAddress] = useState(
    editingLeave?.contactAddress || settings.address || 'อำเภอน้ำพอง จังหวัดขอนแก่น'
  );
  const [contactPhone, setContactPhone] = useState(editingLeave?.contactPhone || user.phone || '');
  const [substituteWork, setSubstituteWork] = useState(editingLeave?.substituteWork || '');
  const [substitutePerson, setSubstitutePerson] = useState(editingLeave?.substitutePerson || '');
  const [note, setNote] = useState(editingLeave?.note || '');
  const [requesterSignatureUrl, setRequesterSignatureUrl] = useState(
    editingLeave?.requesterSignatureUrl ||
      (editingLeave?.halfDayPeriod?.startsWith('data:image/') ? editingLeave.halfDayPeriod : '')
  );

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDownloadingPreviewPdf, setIsDownloadingPreviewPdf] = useState(false);
  const [stepStatus, setStepStatus] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [hasRestoredDraft, setHasRestoredDraft] = useState(false);

  // Automatic Sequential Leave Number Calculation (e.g. LV-2569-0001)
  const autoGeneratedLeaveNumber = useMemo(() => {
    if (editingLeave?.leaveNumber) return editingLeave.leaveNumber;
    const prefix = settings.leaveNumberPrefix || 'LV';
    const fiscalYear = settings.fiscalYear || '2569';
    const pattern = `${prefix}-${fiscalYear}-`;
    let maxSeq = 0;
    existingLeaves.forEach((l) => {
      if (l.leaveNumber && l.leaveNumber.startsWith(pattern)) {
        const numPart = parseInt(l.leaveNumber.replace(pattern, ''), 10);
        if (!isNaN(numPart) && numPart > maxSeq) maxSeq = numPart;
      }
    });
    const nextSeq = String(maxSeq + 1).padStart(4, '0');
    return `${pattern}${nextSeq}`;
  }, [editingLeave?.leaveNumber, existingLeaves, settings.leaveNumberPrefix, settings.fiscalYear]);

  // Restore local draft if creating new leave (#30)
  useEffect(() => {
    if (editingLeave) return;
    try {
      const saved = localStorage.getItem(LOCAL_DRAFT_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed && parsed.reason) {
          setLeaveTypeId(parsed.leaveTypeId || defaultType?.typeId || 'LT-01');
          setSubject(parsed.subject || `ขออนุญาต${defaultType?.name || 'ลาป่วย'}`);
          setDurationType(parsed.durationType || 'เต็มวัน');
          setStartDate(parsed.startDate || getTodayISO());
          setEndDate(parsed.endDate || getTodayISO());
          setReason(parsed.reason || '');
          setContactAddress(parsed.contactAddress || settings.address);
          setContactPhone(parsed.contactPhone || user.phone);
          setSubstituteWork(parsed.substituteWork || '');
          setSubstitutePerson(parsed.substitutePerson || '');
          setNote(parsed.note || '');
          if (parsed.requesterSignatureUrl) setRequesterSignatureUrl(parsed.requesterSignatureUrl);
          setHasRestoredDraft(true);
        }
      }
    } catch {
      // ignore
    }
  }, [editingLeave]);

  // Save draft to localStorage automatically so user never loses form data (#22, #30)
  useEffect(() => {
    if (editingLeave) return;
    try {
      localStorage.setItem(
        LOCAL_DRAFT_KEY,
        JSON.stringify({
          leaveTypeId,
          subject,
          durationType,
          startDate,
          endDate,
          reason,
          contactAddress,
          contactPhone,
          substituteWork,
          substitutePerson,
          note,
          requesterSignatureUrl,
        })
      );
    } catch {
      // ignore
    }
  }, [
    editingLeave,
    leaveTypeId,
    subject,
    durationType,
    startDate,
    endDate,
    reason,
    contactAddress,
    contactPhone,
    substituteWork,
    substitutePerson,
    note,
    requesterSignatureUrl,
  ]);

  const selectedLeaveType = useMemo(
    () => leaveTypes.find((lt) => lt.typeId === leaveTypeId),
    [leaveTypes, leaveTypeId]
  );

  const handleLeaveTypeChange = (newTypeId: string) => {
    setLeaveTypeId(newTypeId);
    const found = leaveTypes.find((lt) => lt.typeId === newTypeId);
    if (found) {
      setSubject(`ขออนุญาต${found.name}`);
    }
  };

  // Auto-calculate total days (#12)
  const totalDays = useMemo(() => {
    const effEnd = durationType.includes('ครึ่งวัน') ? startDate : endDate;
    return calculateLeaveDays(startDate, effEnd, durationType, excludeWeekends);
  }, [startDate, endDate, durationType, excludeWeekends]);

  // Calculate user's previous leave statistics of same category in this fiscal year
  const userLeaveStats = useMemo(() => {
    const userApprovedLeaves = existingLeaves
      .filter(
        (l) =>
          l.userId === user.userId &&
          l.status === 'อนุมัติแล้ว' &&
          l.leaveId !== editingLeave?.leaveId
      )
      .sort((a, b) => (b.startDate || '').localeCompare(a.startDate || ''));

    const lastSameType = userApprovedLeaves.find((l) => l.leaveTypeId === leaveTypeId);
    const accumulated = userApprovedLeaves
      .filter((l) => l.leaveTypeId === leaveTypeId)
      .reduce((sum, l) => sum + (Number(l.totalDays) || 0), 0);

    return {
      lastLeaveType: lastSameType?.leaveTypeName || selectedLeaveType?.name || 'ลาป่วย',
      lastLeaveStartDate: lastSameType?.startDate || '',
      lastLeaveEndDate: lastSameType?.endDate || '',
      lastLeaveTotalDays: lastSameType?.totalDays || 0,
      accumulatedLeaveDays: accumulated,
    };
  }, [existingLeaves, user.userId, editingLeave?.leaveId, leaveTypeId, selectedLeaveType?.name]);

  const defaultInspector = useMemo(
    () =>
      inspectors.find((i) => i.isDefault && i.isActive) ||
      inspectors.find((i) => i.isActive),
    [inspectors]
  );

  // Build Live Preview Leave Request Object for Official Thai Government A4 Form & Real PDF
  const livePreviewLeave: LeaveRequest = useMemo(() => {
    const effectiveEndDate = durationType.includes('ครึ่งวัน') ? startDate : endDate;
    return {
      leaveId: editingLeave?.leaveId || 'PREVIEW-LIVE',
      leaveNumber: autoGeneratedLeaveNumber,
      userId: user.userId,
      username: user.username,
      fullName: user.fullName,
      position: requesterPosition || user.position || '-',
      department: requesterDepartment || user.department || settings.organizationName,
      role: user.role,
      writtenDate,
      subject: subject || `ขออนุญาต${selectedLeaveType?.name || 'ลาป่วย'}`,
      addressedTo: addressedTo || settings.addressedToDefault,
      leaveTypeId,
      leaveTypeName: selectedLeaveType?.name || 'ลาป่วย',
      startDate,
      endDate: effectiveEndDate,
      durationType,
      halfDayPeriod: requesterSignatureUrl || durationType,
      requesterSignatureUrl,
      totalDays: totalDays > 0 ? totalDays : 0,
      reason: reason || '-',
      contactAddress: contactAddress || settings.address,
      contactPhone: contactPhone || user.phone || '-',
      substituteWork: substituteWork || '-',
      substitutePerson: substitutePerson || '-',
      note: note || '',
      status: editingLeave?.status || 'รอตรวจสอบ',
      lastLeaveType: editingLeave?.lastLeaveType || userLeaveStats.lastLeaveType,
      lastLeaveStartDate: editingLeave?.lastLeaveStartDate ?? userLeaveStats.lastLeaveStartDate,
      lastLeaveEndDate: editingLeave?.lastLeaveEndDate ?? userLeaveStats.lastLeaveEndDate,
      lastLeaveTotalDays: editingLeave?.lastLeaveTotalDays ?? userLeaveStats.lastLeaveTotalDays,
      accumulatedLeaveDays:
        editingLeave?.accumulatedLeaveDays ?? userLeaveStats.accumulatedLeaveDays,
      inspectorName:
        editingLeave?.inspectorName ||
        defaultInspector?.fullName ||
        settings.defaultInspectorName,
      inspectorPosition:
        editingLeave?.inspectorPosition ||
        defaultInspector?.position ||
        settings.defaultInspectorPosition,
      inspectorComment: editingLeave?.inspectorComment || '',
      inspectorSignatureUrl: editingLeave?.inspectorSignatureUrl || '',
      inspectedAt: editingLeave?.inspectedAt || '',
      approverName: editingLeave?.approverName || settings.directorName,
      approverPosition: editingLeave?.approverPosition || settings.directorPosition,
      approverComment: editingLeave?.approverComment || '',
      approverSignatureUrl: editingLeave?.approverSignatureUrl || '',
      approvedAt: editingLeave?.approvedAt || '',
      returnReason: editingLeave?.returnReason || '',
      rejectReason: editingLeave?.rejectReason || '',
      pdfFileId: editingLeave?.pdfFileId || '',
      pdfFileUrl: editingLeave?.pdfFileUrl || '',
      pdfWebViewLink: editingLeave?.pdfWebViewLink || '',
      createdAt: editingLeave?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }, [
    editingLeave,
    autoGeneratedLeaveNumber,
    user,
    requesterPosition,
    requesterDepartment,
    settings,
    writtenDate,
    subject,
    selectedLeaveType,
    addressedTo,
    leaveTypeId,
    startDate,
    endDate,
    durationType,
    requesterSignatureUrl,
    totalDays,
    reason,
    contactAddress,
    contactPhone,
    substituteWork,
    substitutePerson,
    note,
    userLeaveStats,
    defaultInspector,
  ]);

  const handleDirectDownloadPdf = async () => {
    try {
      setIsDownloadingPreviewPdf(true);
      const { pdfBlob, fileName } = await generateOfficialLeavePdf(livePreviewLeave, settings);
      const url = URL.createObjectURL(pdfBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 10000);
    } finally {
      setIsDownloadingPreviewPdf(false);
    }
  };

  const handleSave = async (submitNow: boolean) => {
    setErrorMsg('');

    if (!leaveTypeId) {
      setErrorMsg('กรุณาเลือกประเภทการลา');
      return;
    }
    const effectiveEndDate = durationType.includes('ครึ่งวัน') ? startDate : endDate;
    if (!startDate || !effectiveEndDate) {
      setErrorMsg('กรุณาระบุวันที่เริ่มลาและถึงวันที่ให้ครบถ้วน');
      return;
    }
    if (effectiveEndDate < startDate) {
      setErrorMsg('วันที่สิ้นสุดการลาต้องไม่น้อยกว่าวันที่เริ่มลา');
      return;
    }
    if (totalDays <= 0) {
      setErrorMsg('จำนวนวันลาต้องมากกว่า 0 วัน');
      return;
    }
    if (!reason.trim()) {
      setErrorMsg('กรุณากรอกเหตุผลการลา');
      return;
    }
    const phoneClean = contactPhone.replace(/[\s-]/g, '');
    if (!/^[0-9]{9,10}$/.test(phoneClean)) {
      setErrorMsg('กรุณากรอกเบอร์โทรศัพท์ที่ติดต่อได้ระหว่างลา (ตัวเลข 9-10 หลัก)');
      return;
    }

    setIsSubmitting(true);
    try {
      setStepStatus('กำลังรันเลขที่ใบลาอัตโนมัติและบันทึกลงใน Google Sheets...');
      const savedLeave = await onSubmitLeave(
        {
          writtenDate,
          subject,
          addressedTo,
          position: requesterPosition || user.position,
          department: requesterDepartment || user.department || settings.organizationName,
          leaveTypeId,
          leaveTypeName: selectedLeaveType?.name || 'ลาป่วย',
          startDate,
          endDate: effectiveEndDate,
          durationType,
          requesterSignatureUrl,
          totalDays,
          reason,
          contactAddress,
          contactPhone,
          substituteWork,
          substitutePerson,
          note,
          submitNow,
        },
        editingLeave?.leaveId
      );

      // Clear local draft once saved to Google Sheets
      try {
        localStorage.removeItem(LOCAL_DRAFT_KEY);
      } catch {
        // ignore
      }

      // Generate official A4 PDF (TH-Sarabun-PSK 16pt) and upload to Google Drive (#15)
      let finalLeave = savedLeave;
      try {
        setStepStatus(
          'กำลังสร้างโฟลเดอร์ Google Drive อัตโนมัติ และบันทึก PDF พร้อม File ID/URL ลง Google Sheets...'
        );
        const { pdfBase64, fileName } = await generateOfficialLeavePdf(savedLeave, settings);
        const uploadedLeave = await onUploadPdfToDrive(savedLeave.leaveId, pdfBase64, fileName);
        if (uploadedLeave) {
          finalLeave = uploadedLeave;
        }
      } catch {
        // Non-fatal if Drive upload is retried in preview screen
      }

      onFinished(finalLeave);
    } catch (err: any) {
      setErrorMsg(
        err.message ||
          'ไม่สามารถเชื่อมต่อ Google Sheets ได้ ระบบได้เก็บข้อมูลของคุณไว้ในแบบฟอร์มแล้ว กรุณาตรวจสอบการเชื่อมต่อแล้วกดลองใหม่'
      );
    } finally {
      setIsSubmitting(false);
      setStepStatus('');
    }
  };

  return (
    <div className="space-y-4">
      {/* Top Official Banner: Automatic Leave Number + TH-Sarabun-PSK 16pt A4 Controls */}
      <div className="no-print bg-white rounded-3xl border border-slate-200 shadow-xs p-4 sm:p-5 space-y-3.5">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                <FilePlus2 className="w-5 h-5 text-indigo-800" />
                {editingLeave
                  ? `แก้ไขใบลาราชการ เลขที่ ${editingLeave.leaveNumber}`
                  : 'สร้างใบลาราชการไทย (A4 • TH-Sarabun-PSK 16 pt)'}
              </h2>
              <span className="px-3 py-1 rounded-xl bg-indigo-950 text-amber-300 font-mono text-xs font-bold shadow-2xs">
                เลขที่ใบลาอัตโนมัติ: {autoGeneratedLeaveNumber}
              </span>
            </div>
            <p className="text-xs text-slate-500">
              แบบฟอร์มมาตรฐานราชการไทย ขนาด A4 (210 × 297 มม.) • ฟอนต์{' '}
              <strong className="text-slate-700">TH-Sarabun-PSK 16 pt</strong> • สร้างไฟล์ PDF จริงและรันเลขทะเบียนใบลาอัตโนมัติ
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={handleDirectDownloadPdf}
              disabled={isDownloadingPreviewPdf}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-indigo-900 hover:bg-indigo-800 text-white text-xs font-bold shadow-xs transition cursor-pointer disabled:opacity-60"
            >
              {isDownloadingPreviewPdf ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Download className="w-4 h-4" />
              )}
              สร้างและดาวน์โหลด PDF จริง (.pdf)
            </button>

            {hasRestoredDraft && !editingLeave && (
              <button
                type="button"
                onClick={() => {
                  localStorage.removeItem(LOCAL_DRAFT_KEY);
                  setReason('');
                  setRequesterSignatureUrl('');
                  setHasRestoredDraft(false);
                }}
                className="px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-xs text-slate-700 font-medium cursor-pointer"
              >
                ล้างร่างที่ค้างไว้
              </button>
            )}
          </div>
        </div>

        {/* View Mode Switcher */}
        <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-slate-100">
          <div className="inline-flex rounded-2xl bg-slate-100 p-1 gap-1">
            <button
              type="button"
              onClick={() => setViewMode('split')}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition cursor-pointer ${
                viewMode === 'split'
                  ? 'bg-white text-indigo-950 shadow-2xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              กรอกข้อมูล + กระดาษ A4 สด
            </button>
            <button
              type="button"
              onClick={() => setViewMode('form')}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition cursor-pointer ${
                viewMode === 'form'
                  ? 'bg-white text-indigo-950 shadow-2xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              เฉพาะฟอร์มกรอกข้อมูล
            </button>
            <button
              type="button"
              onClick={() => setViewMode('a4_preview')}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition cursor-pointer ${
                viewMode === 'a4_preview'
                  ? 'bg-white text-indigo-950 shadow-2xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              ดูแบบฟอร์มราชการ A4 เต็มหน้า (TH-Sarabun-PSK 16 pt)
            </button>
          </div>

          <div className="text-[11px] text-slate-500">
            ปีงบประมาณ พ.ศ. <strong>{settings.fiscalYear || '2569'}</strong> • ลำดับถัดไป:{' '}
            <strong className="text-indigo-900 font-mono">{autoGeneratedLeaveNumber}</strong>
          </div>
        </div>
      </div>

      {editingLeave?.returnReason && (
        <div className="no-print p-3.5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 text-xs space-y-1">
          <div className="font-bold flex items-center gap-1.5">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            ข้อความแจ้งให้แก้ไขจากผู้ตรวจสอบ:
          </div>
          <div>{editingLeave.returnReason}</div>
        </div>
      )}

      {errorMsg && (
        <div className="no-print p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 text-xs space-y-1.5">
          <div className="font-bold flex items-center gap-1.5">
            <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0" />
            ไม่สามารถบันทึกข้อมูลได้ (ข้อมูลในแบบฟอร์มไม่สูญหาย):
          </div>
          <p>{errorMsg}</p>
        </div>
      )}

      <div
        className={
          viewMode === 'split'
            ? 'grid grid-cols-1 xl:grid-cols-12 gap-5 items-start'
            : 'space-y-5'
        }
      >
        {/* LEFT / FORM PANEL */}
        {viewMode !== 'a4_preview' && (
          <div
            className={`${
              viewMode === 'split' ? 'xl:col-span-5' : ''
            } no-print bg-white rounded-3xl border border-slate-200 shadow-xs p-4 sm:p-6 space-y-5`}
          >
            {/* Automatic Leave Number & Requester Official Header */}
            <div className="bg-indigo-950 text-white rounded-2xl p-3.5 space-y-2">
              <div className="flex items-center justify-between gap-2">
                <span className="text-[11px] text-indigo-200 font-medium">
                  เลขทะเบียนใบลาอัตโนมัติ
                </span>
                <span className="px-2.5 py-0.5 rounded-lg bg-amber-400 text-slate-950 font-mono text-xs font-bold">
                  {autoGeneratedLeaveNumber}
                </span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 text-xs pt-1 border-t border-white/10">
                <div>
                  <span className="text-indigo-300">ข้าพเจ้า:</span>{' '}
                  <span className="font-bold">{user.fullName}</span>
                </div>
                <div>
                  <span className="text-indigo-300">ประเภทบุคลากร:</span>{' '}
                  <span className="font-semibold text-amber-200">{user.role}</span>
                </div>
              </div>
            </div>

            {/* Form Inputs */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  วันที่เขียนใบลา ({formatThaiDate(writtenDate)}) *
                </label>
                <input
                  type="date"
                  value={writtenDate}
                  onChange={(e) => setWrittenDate(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm focus:outline-none focus:border-indigo-700"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">ประเภทการลา *</label>
                <select
                  value={leaveTypeId}
                  onChange={(e) => handleLeaveTypeChange(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm bg-white focus:outline-none focus:border-indigo-700 font-semibold text-indigo-950"
                >
                  {activeLeaveTypes.map((lt) => (
                    <option key={lt.typeId} value={lt.typeId}>
                      {lt.name} (เพดาน {lt.maxDaysPerYear} วัน)
                    </option>
                  ))}
                </select>
                {selectedLeaveType?.conditionText && (
                  <p className="text-[11px] text-slate-500 mt-1">
                    เงื่อนไข: {selectedLeaveType.conditionText}
                  </p>
                )}
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">เรื่อง *</label>
                <input
                  type="text"
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">เรียน *</label>
                <input
                  type="text"
                  value={addressedTo}
                  onChange={(e) => setAddressedTo(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">ตำแหน่ง *</label>
                <input
                  type="text"
                  value={requesterPosition}
                  onChange={(e) => setRequesterPosition(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  สังกัด / เขียนที่ *
                </label>
                <input
                  type="text"
                  value={requesterDepartment}
                  onChange={(e) => setRequesterDepartment(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              {/* Duration Type Selection */}
              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                  รูปแบบระยะเวลาการลา *
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  {(
                    [
                      'เต็มวัน',
                      'ครึ่งวันเช้า (08.30 - 12.00 น.)',
                      'ครึ่งวันบ่าย (13.00 - 16.30 น.)',
                    ] as LeaveDurationType[]
                  ).map((dt) => (
                    <button
                      key={dt}
                      type="button"
                      onClick={() => {
                        setDurationType(dt);
                        if (dt.includes('ครึ่งวัน')) {
                          setEndDate(startDate);
                        }
                      }}
                      className={`py-2.5 px-3 rounded-xl border text-xs font-semibold transition cursor-pointer ${
                        durationType === dt
                          ? 'bg-indigo-900 text-white border-indigo-900 shadow-xs'
                          : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                      }`}
                    >
                      {dt}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  ตั้งแต่วันที่ ({formatThaiDate(startDate)}) *
                </label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => {
                    setStartDate(e.target.value);
                    if (durationType.includes('ครึ่งวัน') || e.target.value > endDate) {
                      setEndDate(e.target.value);
                    }
                  }}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  ถึงวันที่ ({formatThaiDate(durationType.includes('ครึ่งวัน') ? startDate : endDate)}) *
                </label>
                <input
                  type="date"
                  disabled={durationType.includes('ครึ่งวัน')}
                  min={startDate}
                  value={durationType.includes('ครึ่งวัน') ? startDate : endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm disabled:bg-slate-100"
                />
              </div>

              {/* Auto-calculated Total Days & Fiscal Year Stats Summary */}
              <div className="sm:col-span-2 bg-indigo-50/80 border border-indigo-200 rounded-2xl p-3.5 space-y-2">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4 text-indigo-800" />
                    <div className="text-xs text-indigo-950 font-semibold">
                      ลาครั้งนี้:{' '}
                      <span className="text-sm font-bold text-indigo-900">
                        {totalDays > 0 ? totalDays : 0} วัน
                      </span>{' '}
                      • ลามาแล้วปีงบฯ นี้:{' '}
                      <span className="font-bold">{userLeaveStats.accumulatedLeaveDays} วัน</span> • รวมเป็น:{' '}
                      <span className="font-bold text-emerald-800">
                        {userLeaveStats.accumulatedLeaveDays + (totalDays > 0 ? totalDays : 0)} วัน
                      </span>
                    </div>
                  </div>

                  {!durationType.includes('ครึ่งวัน') && (
                    <label className="flex items-center gap-1.5 text-xs font-medium text-indigo-900 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={excludeWeekends}
                        onChange={(e) => setExcludeWeekends(e.target.checked)}
                        className="rounded text-indigo-900"
                      />
                      ไม่นับเสาร์-อาทิตย์
                    </label>
                  )}
                </div>
              </div>

              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  เหตุผลการลา (เนื่องจาก) *
                </label>
                <textarea
                  rows={2}
                  required
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                  placeholder="ระบุเหตุผลการลาอย่างชัดเจนตามระเบียบราชการ..."
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  ในระหว่างลาติดต่อข้าพเจ้าได้ที่ *
                </label>
                <input
                  type="text"
                  value={contactAddress}
                  onChange={(e) => setContactAddress(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  เบอร์โทรศัพท์ติดต่อระหว่างลา *
                </label>
                <input
                  type="tel"
                  value={contactPhone}
                  onChange={(e) => setContactPhone(e.target.value)}
                  placeholder="08X-XXXXXXX"
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  มอบหมายงานในหน้าที่ให้ (ชื่อผู้รับมอบ)
                </label>
                <input
                  type="text"
                  value={substitutePerson}
                  onChange={(e) => setSubstitutePerson(e.target.value)}
                  placeholder="ระบุชื่อ-นามสกุลผู้ปฏิบัติงานแทน (ถ้ามี)"
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  งานที่มอบหมายให้รับผิดชอบแทน
                </label>
                <input
                  type="text"
                  value={substituteWork}
                  onChange={(e) => setSubstituteWork(e.target.value)}
                  placeholder="เช่น งานการเรียนการสอน / งานธุรการ"
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  หมายเหตุเพิ่มเติม
                </label>
                <input
                  type="text"
                  value={note}
                  onChange={(e) => setNote(e.target.value)}
                  placeholder="ระบุหมายเหตุเพิ่มเติม (ถ้ามี)"
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              {/* Requester Digital Signature Pad */}
              <div className="sm:col-span-2 pt-1">
                <SignaturePad
                  label="ลงลายมือชื่อผู้ขอลา (แสดงบนแบบฟอร์มราชการไทย A4 และในไฟล์ PDF จริง)"
                  value={requesterSignatureUrl}
                  onChange={setRequesterSignatureUrl}
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="pt-4 border-t border-slate-100 flex flex-wrap items-center justify-end gap-2.5">
              {onCancelEdit && (
                <button
                  type="button"
                  onClick={onCancelEdit}
                  className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold cursor-pointer"
                >
                  ยกเลิก
                </button>
              )}

              <button
                type="button"
                disabled={isSubmitting}
                onClick={() => handleSave(false)}
                className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-slate-200 hover:bg-slate-300 text-slate-800 text-xs font-semibold transition cursor-pointer disabled:opacity-60"
              >
                <Save className="w-4 h-4" />
                บันทึกฉบับร่าง
              </button>

              <button
                type="button"
                disabled={isSubmitting}
                onClick={() => handleSave(true)}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-900 to-purple-900 hover:from-indigo-800 hover:to-purple-800 text-white text-xs font-bold shadow-sm transition cursor-pointer disabled:opacity-60"
              >
                {isSubmitting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Send className="w-4 h-4" />
                )}
                {isSubmitting
                  ? stepStatus || 'กำลังส่งใบลา...'
                  : `ยืนยันส่งใบลา (${autoGeneratedLeaveNumber}) และสร้าง PDF จริง`}
              </button>
            </div>
          </div>
        )}

        {/* RIGHT / LIVE OFFICIAL THAI GOVERNMENT A4 FORM PREVIEW (TH-Sarabun-PSK 16 pt) */}
        {viewMode !== 'form' && (
          <div className={viewMode === 'split' ? 'xl:col-span-7' : ''}>
            <OfficialLeaveDocument
              leave={livePreviewLeave}
              settings={settings}
              onUploadToDrive={editingLeave ? onUploadPdfToDrive : undefined}
              compactToolbar={viewMode === 'split'}
            />
          </div>
        )}
      </div>
    </div>
  );
};

// ============================================================================
// LEAVE LIST, SEARCH/FILTER, HISTORY & INSPECTOR/ADMIN APPROVAL WORKFLOW (#16-#21)
// ============================================================================
interface LeaveListAndInspectionViewProps {
  user: User;
  canReviewAllLeaves: boolean;
  leaves: LeaveRequest[];
  leaveTypes: LeaveType[];
  inspectors: InspectorRecord[];
  settings: SystemSettings;
  mode: 'my_leaves' | 'history' | 'review';
  onEditLeave: (leave: LeaveRequest) => void;
  onCancelLeave: (leaveId: string) => Promise<void>;
  onWorkflowAction: (
    leaveId: string,
    payload: {
      actionType: 'ตรวจสอบ' | 'อนุมัติ' | 'ไม่อนุมัติ' | 'ส่งกลับแก้ไข';
      comment: string;
      actorName: string;
      actorPosition: string;
      signatureDataUrl: string;
    }
  ) => Promise<LeaveRequest>;
  onUploadPdfToDrive: (
    leaveId: string,
    pdfBase64: string,
    fileName: string
  ) => Promise<LeaveRequest | void>;
}

export const LeaveListAndInspectionView: React.FC<LeaveListAndInspectionViewProps> = ({
  user,
  canReviewAllLeaves,
  leaves,
  leaveTypes,
  inspectors,
  settings,
  mode,
  onEditLeave,
  onCancelLeave,
  onWorkflowAction,
  onUploadPdfToDrive,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [typeFilter, setTypeFilter] = useState<string>('ALL');
  const [monthFilter, setMonthFilter] = useState<string>('ALL');
  const [yearFilter, setYearFilter] = useState<string>('ALL');

  const [previewLeave, setPreviewLeave] = useState<LeaveRequest | null>(null);
  const [workflowTarget, setWorkflowTarget] = useState<{
    leave: LeaveRequest;
    actionType: 'ตรวจสอบ' | 'อนุมัติ' | 'ไม่อนุมัติ' | 'ส่งกลับแก้ไข';
  } | null>(null);

  const defaultInspector =
    inspectors.find((i) => i.isDefault && i.isActive) || inspectors[0];

  const [actorName, setActorName] = useState('');
  const [actorPosition, setActorPosition] = useState('');
  const [workflowComment, setWorkflowComment] = useState('');
  const [signatureDataUrl, setSignatureDataUrl] = useState('');
  const [isProcessingWorkflow, setIsProcessingWorkflow] = useState(false);
  const [workflowError, setWorkflowError] = useState('');
  const [uploadingLeaveId, setUploadingLeaveId] = useState<string | null>(null);

  const handleQuickGenerateAndUploadDrive = async (leave: LeaveRequest) => {
    setUploadingLeaveId(leave.leaveId);
    try {
      const { pdfBase64, fileName } = await generateOfficialLeavePdf(leave, settings);
      await onUploadPdfToDrive(leave.leaveId, pdfBase64, fileName);
    } catch {
      // handled in parent or document modal
    } finally {
      setUploadingLeaveId(null);
    }
  };

  const openWorkflowModal = (
    leave: LeaveRequest,
    actionType: 'ตรวจสอบ' | 'อนุมัติ' | 'ไม่อนุมัติ' | 'ส่งกลับแก้ไข'
  ) => {
    setWorkflowError('');
    if (actionType === 'ตรวจสอบ') {
      setActorName(defaultInspector?.fullName || settings.defaultInspectorName || user.fullName);
      setActorPosition(
        defaultInspector?.position ||
          settings.defaultInspectorPosition ||
          'หัวหน้าเจ้าหน้าที่กลุ่มงานบุคคล'
      );
      setWorkflowComment('ตรวจสอบสถิติการลาแล้ว เห็นควรอนุญาต');
      setSignatureDataUrl(defaultInspector?.signatureDataUrl || '');
    } else if (actionType === 'อนุมัติ') {
      setActorName(settings.directorName || user.fullName);
      setActorPosition(settings.directorPosition || 'ผู้อำนวยการสถานศึกษา');
      setWorkflowComment('อนุญาต');
      setSignatureDataUrl(settings.directorSignatureUrl || '');
    } else {
      setActorName(user.fullName);
      setActorPosition(user.position || settings.defaultInspectorPosition);
      setWorkflowComment('');
      setSignatureDataUrl('');
    }
    setWorkflowTarget({ leave, actionType });
  };

  const handleConfirmWorkflow = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!workflowTarget) return;
    const { leave, actionType } = workflowTarget;

    if (
      (actionType === 'ไม่อนุมัติ' || actionType === 'ส่งกลับแก้ไข') &&
      !workflowComment.trim()
    ) {
      setWorkflowError(
        actionType === 'ไม่อนุมัติ'
          ? 'กรุณากรอกเหตุผลที่ไม่อนุมัติใบลา'
          : 'กรุณากรอกข้อความแจ้งผู้ยื่นเพื่อแก้ไขใบลา'
      );
      return;
    }

    setIsProcessingWorkflow(true);
    setWorkflowError('');
    try {
      const updatedLeave = await onWorkflowAction(leave.leaveId, {
        actionType,
        comment: workflowComment,
        actorName,
        actorPosition,
        signatureDataUrl,
      });

      // Regenerate official PDF with inspector/approver signature and re-upload to Google Drive (#15, #16, #18)
      if (actionType === 'ตรวจสอบ' || actionType === 'อนุมัติ' || actionType === 'ไม่อนุมัติ') {
        try {
          const { pdfBase64, fileName } = await generateOfficialLeavePdf(updatedLeave, settings);
          await onUploadPdfToDrive(updatedLeave.leaveId, pdfBase64, fileName);
        } catch {
          // non-fatal
        }
      }

      setWorkflowTarget(null);
    } catch (err: any) {
      setWorkflowError(err.message || 'ไม่สามารถบันทึกผลการพิจารณาได้');
    } finally {
      setIsProcessingWorkflow(false);
    }
  };

  const filteredLeaves = useMemo(() => {
    return leaves.filter((l) => {
      if (mode === 'my_leaves' && l.userId !== user.userId) return false;
      if (mode === 'history' && !canReviewAllLeaves && l.userId !== user.userId) return false;

      if (statusFilter !== 'ALL' && l.status !== statusFilter) return false;
      if (typeFilter !== 'ALL' && l.leaveTypeName !== typeFilter) return false;

      const dateParts = parseISODateParts(l.startDate);
      if (monthFilter !== 'ALL' && dateParts && String(dateParts.monthIndex) !== monthFilter) {
        return false;
      }
      if (yearFilter !== 'ALL' && dateParts && String(dateParts.yearBE) !== yearFilter) {
        return false;
      }

      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const match =
          l.leaveNumber.toLowerCase().includes(q) ||
          l.fullName.toLowerCase().includes(q) ||
          l.position.toLowerCase().includes(q) ||
          l.leaveTypeName.toLowerCase().includes(q) ||
          l.reason.toLowerCase().includes(q);
        if (!match) return false;
      }
      return true;
    });
  }, [leaves, mode, user.userId, canReviewAllLeaves, statusFilter, typeFilter, monthFilter, yearFilter, searchQuery]);

  const getStatusBadgeStyle = (status: string) => {
    switch (status) {
      case 'อนุมัติแล้ว':
        return 'bg-emerald-50 text-emerald-800 border-emerald-200';
      case 'รอตรวจสอบ':
      case 'ส่งใบลาแล้ว':
        return 'bg-amber-50 text-amber-800 border-amber-200';
      case 'รออนุมัติ':
        return 'bg-blue-50 text-blue-800 border-blue-200';
      case 'ส่งกลับแก้ไข':
        return 'bg-orange-50 text-orange-800 border-orange-200';
      case 'ไม่อนุมัติ':
        return 'bg-rose-50 text-rose-800 border-rose-200';
      default:
        return 'bg-slate-100 text-slate-600 border-slate-200';
    }
  };

  if (previewLeave) {
    return (
      <OfficialLeaveDocument
        leave={previewLeave}
        settings={settings}
        onClose={() => setPreviewLeave(null)}
        onUploadToDrive={onUploadPdfToDrive}
      />
    );
  }

  return (
    <div className="space-y-4">
      {/* Header & Search/Filter Panel (#21) */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-xs space-y-3">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div>
            <h2 className="text-lg font-bold text-slate-900">
              {mode === 'review'
                ? 'ตรวจสอบและอนุมัติใบลาราชการ'
                : mode === 'history'
                ? 'ประวัติการลาและค้นหาเอกสาร'
                : 'รายการใบลาของฉัน'}
            </h2>
            <p className="text-xs text-slate-500">
              พบรายการใบลาทั้งหมด {filteredLeaves.length} รายการ
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2.5">
          <div className="relative sm:col-span-2 lg:col-span-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="ค้นหาเลขที่ใบลา, ชื่อ, ตำแหน่ง..."
              className="w-full pl-9 pr-3 py-2 text-xs rounded-xl border border-slate-200 focus:outline-none focus:border-indigo-700"
            />
          </div>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-3 py-2 text-xs rounded-xl border border-slate-200 bg-white"
          >
            <option value="ALL">ทุกสถานะใบลา</option>
            <option value="รอตรวจสอบ">รอตรวจสอบ</option>
            <option value="รออนุมัติ">รออนุมัติ</option>
            <option value="อนุมัติแล้ว">อนุมัติแล้ว</option>
            <option value="ส่งกลับแก้ไข">ส่งกลับแก้ไข</option>
            <option value="ไม่อนุมัติ">ไม่อนุมัติ</option>
            <option value="ร่าง">ฉบับร่าง</option>
            <option value="ยกเลิก">ยกเลิกแล้ว</option>
          </select>

          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="px-3 py-2 text-xs rounded-xl border border-slate-200 bg-white"
          >
            <option value="ALL">ทุกประเภทการลา</option>
            {leaveTypes.map((lt) => (
              <option key={lt.typeId} value={lt.name}>
                {lt.name}
              </option>
            ))}
          </select>

          <select
            value={monthFilter}
            onChange={(e) => setMonthFilter(e.target.value)}
            className="px-3 py-2 text-xs rounded-xl border border-slate-200 bg-white"
          >
            <option value="ALL">ทุกเดือน</option>
            {Array.from({ length: 12 }).map((_, idx) => (
              <option key={idx} value={String(idx)}>
                {getThaiMonthName(idx)}
              </option>
            ))}
          </select>

          <select
            value={yearFilter}
            onChange={(e) => setYearFilter(e.target.value)}
            className="px-3 py-2 text-xs rounded-xl border border-slate-200 bg-white"
          >
            <option value="ALL">ทุกปี พ.ศ.</option>
            <option value="2569">พ.ศ. 2569</option>
            <option value="2568">พ.ศ. 2568</option>
            <option value="2570">พ.ศ. 2570</option>
          </select>
        </div>
      </div>

      {/* Leave Cards List */}
      {filteredLeaves.length === 0 ? (
        <div className="bg-white rounded-3xl p-10 text-center border border-slate-200 space-y-2">
          <FileText className="w-10 h-10 text-slate-300 mx-auto" />
          <div className="text-sm font-semibold text-slate-700">ไม่พบรายการใบลาตามเงื่อนไขที่ค้นหา</div>
          <p className="text-xs text-slate-400">คุณสามารถกดปุ่ม &ldquo;สร้างใบลา&rdquo; เพื่อยื่นใบลาออนไลน์ใหม่ได้ทันที</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredLeaves.map((leave) => {
            const isOwner = leave.userId === user.userId;
            const canEdit =
              (isOwner && (leave.status === 'ร่าง' || leave.status === 'ส่งกลับแก้ไข')) ||
              user.role === 'Admin';
            const canCancel =
              (isOwner || user.role === 'Admin') &&
              leave.status !== 'ยกเลิก' &&
              leave.status !== 'ไม่อนุมัติ';

            return (
              <div
                key={leave.leaveId}
                className="bg-white rounded-2xl p-4 border border-slate-200 shadow-xs hover:border-indigo-200 transition space-y-3"
              >
                <div className="flex items-start justify-between gap-2 flex-wrap">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-mono text-xs font-bold px-2.5 py-0.5 rounded-lg bg-indigo-50 text-indigo-950 border border-indigo-200">
                        {leave.leaveNumber}
                      </span>
                      <span className="font-bold text-slate-900 text-sm">
                        {leave.leaveTypeName} ({leave.totalDays} วัน)
                      </span>
                      <span
                        className={`text-[11px] font-semibold px-2.5 py-0.5 rounded-lg border ${getStatusBadgeStyle(
                          leave.status
                        )}`}
                      >
                        {leave.status}
                      </span>
                    </div>

                    <div className="text-xs text-slate-700 font-medium">
                      ผู้ยื่นลา: <span className="font-bold text-slate-900">{leave.fullName}</span> • ตำแหน่ง:{' '}
                      {leave.position || '-'} ({leave.role})
                    </div>

                    <div className="text-xs text-slate-600 flex items-center gap-1.5 flex-wrap">
                      <Calendar className="w-3.5 h-3.5 text-indigo-700" />
                      <span>
                        วันที่ลา: <strong>{formatThaiDate(leave.startDate)}</strong> ถึง{' '}
                        <strong>{formatThaiDate(leave.endDate)}</strong> ({leave.durationType})
                      </span>
                    </div>

                    <div className="text-xs text-slate-600">
                      เหตุผล: <span className="text-slate-800">{leave.reason}</span>
                    </div>

                    {leave.returnReason && (
                      <div className="text-xs text-orange-800 bg-orange-50 px-3 py-1.5 rounded-xl border border-orange-200">
                        <strong>ส่งกลับแก้ไข:</strong> {leave.returnReason}
                      </div>
                    )}
                    {leave.rejectReason && (
                      <div className="text-xs text-rose-800 bg-rose-50 px-3 py-1.5 rounded-xl border border-rose-200">
                        <strong>เหตุผลที่ไม่อนุมัติ:</strong> {leave.rejectReason}
                      </div>
                    )}

                    {/* Google Drive File ID & URL Record Box (Synced with Google Sheets) */}
                    {leave.pdfFileId ? (
                      <div className="mt-2 p-2.5 rounded-xl bg-emerald-50/70 border border-emerald-200 text-[11px] text-emerald-950 flex flex-wrap items-center justify-between gap-2">
                        <div className="space-y-0.5 min-w-0">
                          <div className="font-bold text-emerald-900 flex items-center gap-1.5 flex-wrap">
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                            <span>บันทึกใน Google Drive &amp; Google Sheets แล้ว</span>
                            <span className="font-mono text-[10px] px-1.5 py-0.5 rounded bg-white border border-emerald-200 text-emerald-900">
                              File ID: {leave.pdfFileId}
                            </span>
                          </div>
                          <div className="text-[10px] text-emerald-800 font-mono truncate max-w-xl">
                            URL:{' '}
                            {leave.pdfWebViewLink ||
                              `https://drive.google.com/file/d/${leave.pdfFileId}/view`}
                          </div>
                        </div>
                        <div className="flex items-center gap-1.5 shrink-0">
                          <a
                            href={
                              leave.pdfWebViewLink ||
                              `https://drive.google.com/file/d/${leave.pdfFileId}/view`
                            }
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-white text-[11px] font-semibold"
                          >
                            <ExternalLink className="w-3 h-3" />
                            เปิดใน Drive
                          </a>
                          {leave.pdfFileUrl && (
                            <a
                              href={leave.pdfFileUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="inline-flex items-center gap-1 px-2 py-1 rounded-lg bg-white hover:bg-emerald-100 text-emerald-900 border border-emerald-300 text-[11px] font-semibold"
                            >
                              <Download className="w-3 h-3" />
                              ดาวน์โหลด
                            </a>
                          )}
                        </div>
                      </div>
                    ) : (
                      <div className="mt-2 p-2 rounded-xl bg-amber-50/70 border border-amber-200 text-[11px] text-amber-900 flex flex-wrap items-center justify-between gap-2">
                        <span>
                          ยังไม่ได้อัปโหลด PDF ขึ้นโฟลเดอร์ Google Drive (คลิกเพื่อสร้างโฟลเดอร์และบันทึก File ID/URL อัตโนมัติ)
                        </span>
                        <button
                          type="button"
                          onClick={() => handleQuickGenerateAndUploadDrive(leave)}
                          disabled={uploadingLeaveId === leave.leaveId}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold text-[11px] cursor-pointer disabled:opacity-60"
                        >
                          {uploadingLeaveId === leave.leaveId ? (
                            <Loader2 className="w-3 h-3 animate-spin" />
                          ) : (
                            <ExternalLink className="w-3 h-3" />
                          )}
                          {uploadingLeaveId === leave.leaveId
                            ? 'กำลังอัปโหลด...'
                            : 'สร้าง PDF & บันทึกลง Google Drive'}
                        </button>
                      </div>
                    )}
                  </div>

                  <div className="text-right text-[11px] text-slate-400 space-y-0.5">
                    <div>ยื่นเมื่อ: {formatThaiDate(leave.writtenDate)}</div>
                    {leave.inspectedAt && <div>ผู้ตรวจ: {leave.inspectorName}</div>}
                    {leave.approvedAt && (
                      <div className="text-emerald-700 font-medium">
                        ผู้อนุมัติ: {leave.approverName} ({formatThaiDate(leave.approvedAt)})
                      </div>
                    )}
                  </div>
                </div>

                {/* Action Bar */}
                <div className="pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-2">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <button
                      type="button"
                      onClick={() => setPreviewLeave(leave)}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-50 hover:bg-indigo-100 text-indigo-900 text-xs font-semibold transition cursor-pointer"
                    >
                      <Eye className="w-3.5 h-3.5" />
                      เปิดเอกสารราชการ / PDF
                    </button>

                    {leave.pdfWebViewLink && (
                      <a
                        href={leave.pdfWebViewLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-medium transition"
                      >
                        <ExternalLink className="w-3.5 h-3.5" />
                        Google Drive
                      </a>
                    )}

                    {canEdit && (
                      <button
                        type="button"
                        onClick={() => onEditLeave(leave)}
                        className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-amber-50 hover:bg-amber-100 text-amber-900 border border-amber-200 text-xs font-semibold transition cursor-pointer"
                      >
                        <Edit3 className="w-3.5 h-3.5" />
                        แก้ไขใบลา
                      </button>
                    )}

                    {canCancel && (
                      <button
                        type="button"
                        onClick={() => {
                          if (window.confirm(`ยืนยันการยกเลิกใบลาเลขที่ ${leave.leaveNumber}?`)) {
                            onCancelLeave(leave.leaveId);
                          }
                        }}
                        className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl text-rose-600 hover:bg-rose-50 text-xs font-medium transition cursor-pointer"
                      >
                        <Ban className="w-3.5 h-3.5" />
                        ยกเลิก
                      </button>
                    )}
                  </div>

                  {/* Inspector / Admin Review Controls (#19) */}
                  {canReviewAllLeaves &&
                    leave.status !== 'ยกเลิก' &&
                    leave.status !== 'ร่าง' && (
                      <div className="flex flex-wrap items-center gap-1.5">
                        {(leave.status === 'รอตรวจสอบ' || leave.status === 'ส่งใบลาแล้ว') && (
                          <button
                            type="button"
                            onClick={() => openWorkflowModal(leave, 'ตรวจสอบ')}
                            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs transition cursor-pointer"
                          >
                            <CheckCheck className="w-3.5 h-3.5" />
                            ลงชื่อตรวจสอบ
                          </button>
                        )}

                        {leave.status !== 'อนุมัติแล้ว' && (
                          <button
                            type="button"
                            onClick={() => openWorkflowModal(leave, 'อนุมัติ')}
                            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-xs transition cursor-pointer"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            อนุมัติใบลา
                          </button>
                        )}

                        {leave.status !== 'อนุมัติแล้ว' && (
                          <button
                            type="button"
                            onClick={() => openWorkflowModal(leave, 'ส่งกลับแก้ไข')}
                            className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-amber-100 hover:bg-amber-200 text-amber-900 text-xs font-semibold transition cursor-pointer"
                          >
                            <RotateCcw className="w-3.5 h-3.5" />
                            ส่งกลับแก้ไข
                          </button>
                        )}

                        {leave.status !== 'ไม่อนุมัติ' && (
                          <button
                            type="button"
                            onClick={() => openWorkflowModal(leave, 'ไม่อนุมัติ')}
                            className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-semibold transition cursor-pointer"
                          >
                            <XCircle className="w-3.5 h-3.5" />
                            ไม่อนุมัติ
                          </button>
                        )}
                      </div>
                    )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Inspector / Director Workflow & Signature Modal (#18, #19) */}
      {workflowTarget && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-3xl max-w-lg w-full p-5 shadow-xl space-y-4 my-8">
            <div className="border-b border-slate-100 pb-3">
              <h3 className="text-base font-bold text-slate-900">
                {workflowTarget.actionType === 'ตรวจสอบ' && 'ลงชื่อผู้ตรวจสอบสถิติการลา'}
                {workflowTarget.actionType === 'อนุมัติ' && 'อนุมัติใบลาราชการและประทับลายมือชื่อ'}
                {workflowTarget.actionType === 'ไม่อนุมัติ' && 'ระบุเหตุผลที่ไม่อนุมัติใบลา'}
                {workflowTarget.actionType === 'ส่งกลับแก้ไข' && 'ส่งกลับใบลาให้ผู้ยื่นแก้ไข'}
              </h3>
              <p className="text-xs text-slate-500">
                เลขที่ใบลา: {workflowTarget.leave.leaveNumber} • ผู้ลา: {workflowTarget.leave.fullName} (
                {workflowTarget.leave.leaveTypeName} {workflowTarget.leave.totalDays} วัน)
              </p>
            </div>

            {workflowError && (
              <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium">
                {workflowError}
              </div>
            )}

            <form onSubmit={handleConfirmWorkflow} className="space-y-3">
              {workflowTarget.actionType === 'ตรวจสอบ' && inspectors.length > 0 && (
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">
                    เลือกผู้ตรวจสอบที่ตั้งค่าไว้
                  </label>
                  <select
                    onChange={(e) => {
                      const found = inspectors.find((i) => i.inspectorId === e.target.value);
                      if (found) {
                        setActorName(found.fullName);
                        setActorPosition(found.position);
                        if (found.signatureDataUrl) setSignatureDataUrl(found.signatureDataUrl);
                      }
                    }}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 text-sm bg-slate-50"
                  >
                    {inspectors.map((i) => (
                      <option key={i.inspectorId} value={i.inspectorId}>
                        {i.fullName} ({i.position})
                      </option>
                    ))}
                  </select>
                </div>
              )}

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">
                    ชื่อผู้ลงนาม *
                  </label>
                  <input
                    type="text"
                    required
                    value={actorName}
                    onChange={(e) => setActorName(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 text-sm"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">
                    ตำแหน่ง *
                  </label>
                  <input
                    type="text"
                    required
                    value={actorPosition}
                    onChange={(e) => setActorPosition(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 text-sm"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  {workflowTarget.actionType === 'ไม่อนุมัติ'
                    ? 'เหตุผลที่ไม่อนุมัติ *'
                    : workflowTarget.actionType === 'ส่งกลับแก้ไข'
                    ? 'ข้อความแจ้งให้ผู้ยื่นแก้ไข *'
                    : 'ความเห็นประกอบ'}
                </label>
                <textarea
                  rows={2}
                  required={
                    workflowTarget.actionType === 'ไม่อนุมัติ' ||
                    workflowTarget.actionType === 'ส่งกลับแก้ไข'
                  }
                  value={workflowComment}
                  onChange={(e) => setWorkflowComment(e.target.value)}
                  placeholder="ระบุความเห็นหรือเหตุผล..."
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 text-sm"
                />
              </div>

              {(workflowTarget.actionType === 'ตรวจสอบ' ||
                workflowTarget.actionType === 'อนุมัติ') && (
                <SignaturePad
                  label={`ลายมือชื่อ${
                    workflowTarget.actionType === 'ตรวจสอบ' ? 'ผู้ตรวจสอบ' : 'ผู้อนุมัติ'
                  } (จะแสดงในเอกสาร PDF ทันที)`}
                  value={signatureDataUrl}
                  onChange={setSignatureDataUrl}
                />
              )}

              <div className="flex justify-end gap-2 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setWorkflowTarget(null)}
                  className="px-4 py-2 rounded-xl bg-slate-100 text-slate-700 text-xs font-semibold cursor-pointer"
                >
                  ยกเลิก
                </button>
                <button
                  type="submit"
                  disabled={isProcessingWorkflow}
                  className="inline-flex items-center gap-1.5 px-5 py-2 rounded-xl bg-indigo-900 hover:bg-indigo-800 text-white text-xs font-semibold cursor-pointer disabled:opacity-60"
                >
                  {isProcessingWorkflow && <Loader2 className="w-4 h-4 animate-spin" />}
                  ยืนยัน{workflowTarget.actionType}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
